---
env:
  es2021: true
  browser: true
  node: true

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

globals:
  Atomics: "readonly"
  SharedArrayBuffer: "readonly"

plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
  - prettier
  - eslint-plugin-import-helpers
  - import
  - tailwindcss

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:tailwindcss/recommended

settings:
  react:
    version: detect
  import/resolver:
    typescript:
      project: "."

rules:
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/camelcase": "off"
  "@typescript-eslint/no-empty-interface": "off"
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/explicit-member-accessibility": 0
  "@typescript-eslint/indent": 0
  "@typescript-eslint/member-delimiter-style": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-var-requires": 0
  "@typescript-eslint/no-use-before-define": 0
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
  react/react-in-jsx-scope: 0
  react/display-name: 0
  react/prop-types: "off"
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  prettier/prettier:
    - error
    - endOfLine: auto
  import-helpers/order-imports:
    - warn
    - newlinesBetween: always
      groups:
        - - "/^react/"
        - - module
        - - "/^~//"
        - - "/^@shared/"
        - - parent
          - sibling
          - index
      alphabetize:
        order: asc
        ignoreCase: true
  import/no-duplicates:
    - error
    - considerQueryString: true
  tailwindcss/classnames-order: warn
  tailwindcss/enforces-negative-arbitrary-values: warn
  tailwindcss/enforces-shorthand: warn
  tailwindcss/migration-from-tailwind-2: warn
  tailwindcss/no-arbitrary-value: "off"
  tailwindcss/no-custom-classname: warn
  tailwindcss/no-contradicting-classname: error
  semi: error
  comma-dangle:
    - error
    - arrays: always-multiline
      exports: always-multiline
      functions: never
      imports: always-multiline
      objects: always-multiline
  linebreak-style:
    - error
    - unix
  no-console:
    - warn
    - allow:
        - warn
        - error
  space-before-function-paren:
    - warn
    - anonymous: never
      asyncArrow: always
      named: never
